eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekabook-container:8761/eureka/  # Adjust 'localhost' if the Eureka server is on another host

spring:
  application:
    name: booksecurity
  data:
    mongodb:
      uri: mongodb+srv://anagh11:anagh11@bookcluster.dl7kn.mongodb.net/?retryWrites=true&w=majority&appName=BookCluster
      database: bookdb
server:
  port: 7074




